/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ElectionSystem__factory } from "./ElectionSystem__factory";
export { TrustVote__factory } from "./TrustVote__factory";
